import { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch } from 'react-redux';

import { switchTheme } from 'redux/features/themeSwitcherSlice';
import { updateStatus } from 'redux/features/notificationSlice';

import { Settings } from '@Components/Settings';
import { Title } from '@Components/Title';
import { Switcher } from '@Components/Switcher';
import { RadioGroup } from '@Components/RadioGroup';
import { Notification } from '@Components/Notification';

import { RootState } from 'redux/store';
import { useSelector } from 'react-redux';

import { useThemeContext } from './_app';

const conversation = ['Newest on top', 'Newest on bottom', 'Off'];
const reading = ['Show on the right', 'Show on the bottom', 'Center', 'Hide'];

const Home: NextPage = () => {
  const message = useSelector(
    (state: RootState) => state.noticeReducer.message
  );
  const dispatch = useDispatch();
  const { setTheme } = useThemeContext();

  const darkmode = (val: boolean) => {
    dispatch(switchTheme(val ? 'dark' : 'light'));
    setTheme(val ? 'dark' : 'light');

    dispatch(updateStatus(val ? 'Dark mode is ON' : 'Dark mode is OFF'));
  };
  const notice = (val: boolean) => {
    dispatch(
      updateStatus(
        val ? 'Desktop notification is ON' : 'Desktop notification is OFF'
      )
    );
  };
  const focus = (val: boolean) => {
    dispatch(
      updateStatus(val ? 'Focused inbox is ON' : 'Focused inbox is OFF')
    );
  };
  return (
    <>
      <Head>
        <title>Redux toolkit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Notification message={message} />

      <Settings>
        <Title type="h1">Settings</Title>
        <Switcher name="dark-mode" handler={darkmode}>
          Dark mode
        </Switcher>
        <Switcher name="desktop-notification" handler={notice} active>
          Desktop notification
        </Switcher>
        <Switcher name="focused-inbox" handler={focus}>
          Focused inbox
        </Switcher>
        <Title type="h2">Conversation view</Title>
        <RadioGroup name="Conversation" values={conversation} />
        <Title type="h2">Reading panel</Title>
        <RadioGroup name="Reading" values={reading} defaultRadio={2} />
      </Settings>
    </>
  );
};

export default Home;
